import type {
  Notification,
  DashboardStats,
  Holiday,
  UserAccount,
  ApprovalWorkflow,
  ApprovalRequest,
  RolePermission,
  SystemLog,
  TransactionType,
  EmployeeContractAllowance,
  AllowancePercentage,
  ManualAttendanceRequest,
  AttendanceDayClosure,
  ProjectGPSSettings,
} from '@/types';

export const mockNotifications: Notification[] = [
  {
    notificationId: 1,
    userId: '1234567890',
    notificationType: 'APPROVAL_REQUIRED',
    title: 'Leave Request Pending',
    message: 'Omar Hassan has submitted a leave request pending your approval',
    isRead: false,
    createdDate: new Date('2024-11-25T09:30:00'),
    relatedId: 3001,
    priority: 'M',
  },
  {
    notificationId: 2,
    userId: '1234567890',
    notificationType: 'OVERTIME',
    title: 'High Overtime Alert',
    message: 'Employee Hassan Ahmed has reached 48 overtime hours this month',
    isRead: false,
    createdDate: new Date('2024-11-24T14:15:00'),
    relatedId: 1026,
    priority: 'H',
  },
  {
    notificationId: 3,
    userId: '1234567890',
    notificationType: 'DOCUMENT_EXPIRY',
    title: 'Document Expiring Soon',
    message: '3 residence permits expiring within 14 days',
    isRead: false,
    createdDate: new Date('2024-11-23T10:00:00'),
    priority: 'H',
  },
  {
    notificationId: 4,
    userId: '1234567890',
    notificationType: 'PAYMENT_DUE',
    title: 'Project Payment Due',
    message: 'Payment of SAR 1,416,667 due for Eastern Housing Project on Feb 1, 2025',
    isRead: true,
    createdDate: new Date('2024-11-22T08:00:00'),
    relatedId: 1001,
    priority: 'H',
  },
  {
    notificationId: 5,
    userId: '1234567890',
    notificationType: 'APPROVAL_REQUIRED',
    title: 'Loan Request Pending',
    message: 'Rajesh Kumar has submitted a loan request of SAR 12,000',
    isRead: true,
    createdDate: new Date('2024-11-20T11:45:00'),
    relatedId: 4003,
    priority: 'M',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalEmployees: 62,
  activeEmployees: 58,
  totalProjects: 5,
  activeProjects: 4,
  monthlyPayroll: 1245000,
  pendingApprovals: 5,
  expiringDocuments: 3,
  overtimeAlerts: 2,
};

export const mockHolidays: Holiday[] = [
  {
    serialNo: 1,
    holidayType: 'Fitr',
    gregYear: 2025,
    hijriYear: 1447,
    fromDate: new Date('2025-03-05'),
    toDate: new Date('2025-03-11'),
    numberOfDays: 7,
  },
  {
    serialNo: 2,
    holidayType: 'Adha',
    gregYear: 2025,
    hijriYear: 1447,
    fromDate: new Date('2025-06-05'),
    toDate: new Date('2025-06-15'),
    numberOfDays: 11,
  },
  {
    serialNo: 3,
    holidayType: 'National',
    gregYear: 2025,
    hijriYear: 1447,
    fromDate: new Date('2025-09-23'),
    toDate: new Date('2025-09-23'),
    numberOfDays: 1,
  },
  {
    serialNo: 4,
    holidayType: 'Foundation',
    gregYear: 2026,
    hijriYear: 1447,
    fromDate: new Date('2026-02-22'),
    toDate: new Date('2026-02-22'),
    numberOfDays: 1,
  },
];

export const mockUserAccounts: UserAccount[] = [
  {
    userId: '1234567890',
    username: 'admin',
    userType: 'ADMIN',
    isActive: true,
    lastLoginDate: new Date('2024-11-26'),
    lastLoginTime: '09:15:30',
    createdDate: new Date('2010-01-01'),
    employeeId: 1001,
  },
  {
    userId: '1234567894',
    username: 'hr_manager',
    userType: 'USER',
    isActive: true,
    lastLoginDate: new Date('2024-11-25'),
    lastLoginTime: '08:45:12',
    createdDate: new Date('2013-05-01'),
    employeeId: 1005,
  },
  {
    userId: '1234567899',
    username: 'finance_manager',
    userType: 'USER',
    isActive: true,
    lastLoginDate: new Date('2024-11-26'),
    lastLoginTime: '08:30:00',
    createdDate: new Date('2011-09-01'),
    employeeId: 1010,
  },
  {
    userId: '1234567909',
    username: 'project_manager',
    userType: 'USER',
    isActive: true,
    lastLoginDate: new Date('2024-11-25'),
    lastLoginTime: '07:15:45',
    createdDate: new Date('2010-06-01'),
    employeeId: 1020,
  },
];

export const mockRolePermissions: RolePermission[] = [
  {
    roleName: 'Super Admin',
    description: 'Full system access with all permissions and administrative controls',
    canManageEmployees: true,
    canManageAttendance: true,
    canManageLeave: true,
    canManageLoans: true,
    canManagePayroll: true,
    canManageProjects: true,
    canManageWarehouse: true,
    canViewReports: true,
    canApprove: true,
    canManageSettings: true,
  },
  {
    roleName: 'Admin',
    description: 'Administrative access to manage employees, payroll, and projects',
    canManageEmployees: true,
    canManageAttendance: true,
    canManageLeave: true,
    canManageLoans: true,
    canManagePayroll: true,
    canManageProjects: true,
    canManageWarehouse: true,
    canViewReports: true,
    canApprove: true,
    canManageSettings: true,
  },
  {
    roleName: 'HR Manager',
    description: 'Manage employee records, attendance, and leave requests',
    canManageEmployees: true,
    canManageAttendance: true,
    canManageLeave: true,
    canManageLoans: true,
    canManagePayroll: false,
    canManageProjects: false,
    canManageWarehouse: false,
    canViewReports: true,
    canApprove: true,
    canManageSettings: false,
  },
  {
    roleName: 'Finance Manager',
    description: 'Manage payroll calculations, approvals, and financial reports',
    canManageEmployees: false,
    canManageAttendance: false,
    canManageLeave: false,
    canManageLoans: true,
    canManagePayroll: true,
    canManageProjects: false,
    canManageWarehouse: false,
    canViewReports: true,
    canApprove: true,
    canManageSettings: false,
  },
  {
    roleName: 'Project Manager',
    description: 'Manage projects, payment schedules, and labor assignments',
    canManageEmployees: false,
    canManageAttendance: true,
    canManageLeave: false,
    canManageLoans: false,
    canManagePayroll: false,
    canManageProjects: true,
    canManageWarehouse: false,
    canViewReports: true,
    canApprove: false,
    canManageSettings: false,
  },
  {
    roleName: 'Warehouse Manager',
    description: 'Manage inventory, purchase orders, and warehouse operations',
    canManageEmployees: false,
    canManageAttendance: false,
    canManageLeave: false,
    canManageLoans: false,
    canManagePayroll: false,
    canManageProjects: false,
    canManageWarehouse: true,
    canViewReports: true,
    canApprove: false,
    canManageSettings: false,
  },
  {
    roleName: 'User',
    description: 'Basic user access with limited read-only permissions',
    canManageEmployees: false,
    canManageAttendance: false,
    canManageLeave: false,
    canManageLoans: false,
    canManagePayroll: false,
    canManageProjects: false,
    canManageWarehouse: false,
    canViewReports: false,
    canApprove: false,
    canManageSettings: false,
  },
];

export const mockApprovalRequests: ApprovalRequest[] = [
  {
    requestId: 1,
    requestType: 'LEAVE',
    requestedBy: 1026,
    requestDate: new Date('2024-11-25'),
    priority: 'MEDIUM',
    status: 'PENDING',
    currentLevel: 1,
    notes: 'Annual leave for 5 days',
  },
  {
    requestId: 2,
    requestType: 'LOAN',
    requestedBy: 1032,
    requestDate: new Date('2024-11-24'),
    amount: 15000,
    priority: 'HIGH',
    status: 'PENDING',
    currentLevel: 2,
    notes: 'Personal loan request',
  },
  {
    requestId: 3,
    requestType: 'ALLOWANCE',
    requestedBy: 1045,
    requestDate: new Date('2024-11-23'),
    amount: 2000,
    priority: 'LOW',
    status: 'PENDING',
    currentLevel: 1,
    notes: 'Transportation allowance',
  },
  {
    requestId: 4,
    requestType: 'TRANSFER',
    requestedBy: 1050,
    requestDate: new Date('2024-11-22'),
    priority: 'MEDIUM',
    status: 'PENDING',
    currentLevel: 1,
    notes: 'Transfer to new project',
  },
  {
    requestId: 5,
    requestType: 'PAYMENT',
    requestedBy: 1028,
    requestDate: new Date('2024-11-21'),
    amount: 50000,
    priority: 'HIGH',
    status: 'PENDING',
    currentLevel: 2,
    notes: 'Project payment request',
  },
  {
    requestId: 6,
    requestType: 'LEAVE',
    requestedBy: 1035,
    requestDate: new Date('2024-11-20'),
    priority: 'LOW',
    status: 'APPROVED',
    currentLevel: 3,
    approvedBy: 1001,
    approvalDate: new Date('2024-11-21'),
    notes: 'Sick leave approved',
  },
  {
    requestId: 7,
    requestType: 'LOAN',
    requestedBy: 1040,
    requestDate: new Date('2024-11-19'),
    amount: 8000,
    priority: 'MEDIUM',
    status: 'APPROVED',
    currentLevel: 2,
    approvedBy: 1010,
    approvalDate: new Date('2024-11-20'),
    notes: 'Small loan approved',
  },
  {
    requestId: 8,
    requestType: 'ALLOWANCE',
    requestedBy: 1027,
    requestDate: new Date('2024-11-18'),
    amount: 1500,
    priority: 'LOW',
    status: 'REJECTED',
    currentLevel: 1,
    approvedBy: 1005,
    approvalDate: new Date('2024-11-19'),
    notes: 'Not eligible for this allowance',
  },
];

export const mockApprovalWorkflows: ApprovalWorkflow[] = [
  { requestType: 'VAC', level: 1, functionCall: 'GetDirectManager', closeLevel: 'N', description: 'Direct Manager Approval' },
  { requestType: 'VAC', level: 2, functionCall: 'GetProjectManager', closeLevel: 'N', description: 'Project Manager Approval' },
  { requestType: 'VAC', level: 3, functionCall: 'GetHRManager', closeLevel: 'Y', description: 'HR Manager Final Approval' },

  { requestType: 'LOAN', level: 1, functionCall: 'GetHRManager', closeLevel: 'N', description: 'HR Manager Review' },
  { requestType: 'LOAN', level: 2, functionCall: 'GetFinManager', closeLevel: 'Y', description: 'Finance Manager Approval' },

  { requestType: 'INCR', level: 1, functionCall: 'GetHRManager', closeLevel: 'N', description: 'HR Manager Review' },
  { requestType: 'INCR', level: 2, functionCall: 'GetFinManager', closeLevel: 'Y', description: 'Finance Manager Approval' },

  { requestType: 'POSTLOAN', level: 1, functionCall: 'GetHRManager', closeLevel: 'N', description: 'HR Manager Review' },
  { requestType: 'POSTLOAN', level: 2, functionCall: 'GetFinManager', closeLevel: 'Y', description: 'Finance Manager Approval' },

  { requestType: 'PAYROLL', level: 1, functionCall: 'GetHRManager', closeLevel: 'N', description: 'HR Manager Review' },
  { requestType: 'PAYROLL', level: 2, functionCall: 'GetFinManager', closeLevel: 'N', description: 'Finance Manager Review' },
  { requestType: 'PAYROLL', level: 3, functionCall: 'GetGeneralManager', closeLevel: 'Y', description: 'General Manager Final Approval' },

  { requestType: 'TRANSFER', level: 1, functionCall: 'GetProjectManager', closeLevel: 'N', description: 'Project Manager Approval' },
  { requestType: 'TRANSFER', level: 2, functionCall: 'GetRegionalManager', closeLevel: 'Y', description: 'Regional Manager Approval' },

  { requestType: 'PROJECT_PAYMENT', level: 1, functionCall: 'GetProjectManager', closeLevel: 'N', description: 'Project Manager Review' },
  { requestType: 'PROJECT_PAYMENT', level: 2, functionCall: 'GetFinManager', closeLevel: 'Y', description: 'Finance Manager Approval' },
];

export const mockTransactionTypes: TransactionType[] = [
  {
    transactionCode: 1,
    transactionNameAr: 'راتب أساسي',
    transactionNameEn: 'Basic Salary',
    transactionType: 'ALLOWANCE',
    isSystem: true,
  },
  {
    transactionCode: 2,
    transactionNameAr: 'بدل سكن',
    transactionNameEn: 'Housing Allowance',
    transactionType: 'ALLOWANCE',
    isSystem: true,
  },
  {
    transactionCode: 3,
    transactionNameAr: 'بدل نقل',
    transactionNameEn: 'Transportation Allowance',
    transactionType: 'ALLOWANCE',
    isSystem: true,
  },
  {
    transactionCode: 4,
    transactionNameAr: 'بدل طعام',
    transactionNameEn: 'Food Allowance',
    transactionType: 'ALLOWANCE',
    isSystem: true,
  },
  {
    transactionCode: 5,
    transactionNameAr: 'عمل إضافي',
    transactionNameEn: 'Overtime',
    transactionType: 'ALLOWANCE',
    isSystem: true,
  },
  {
    transactionCode: 6,
    transactionNameAr: 'مكافأة أداء',
    transactionNameEn: 'Performance Bonus',
    transactionType: 'ALLOWANCE',
    isSystem: false,
  },
  {
    transactionCode: 7,
    transactionNameAr: 'علاوة',
    transactionNameEn: 'Salary Increase',
    transactionType: 'ALLOWANCE',
    isSystem: false,
  },
  {
    transactionCode: 10,
    transactionNameAr: 'زيادة على الراتب',
    transactionNameEn: 'Salary Increment',
    transactionType: 'ALLOWANCE',
    isSystem: false,
  },
  {
    transactionCode: 20,
    transactionNameAr: 'حسم غياب',
    transactionNameEn: 'Absence Deduction',
    transactionType: 'DEDUCTION',
    isSystem: true,
  },
  {
    transactionCode: 21,
    transactionNameAr: 'حسم تأخير',
    transactionNameEn: 'Late Arrival Deduction',
    transactionType: 'DEDUCTION',
    isSystem: true,
  },
  {
    transactionCode: 22,
    transactionNameAr: 'حسم انصراف مبكر',
    transactionNameEn: 'Early Departure Deduction',
    transactionType: 'DEDUCTION',
    isSystem: true,
  },
  {
    transactionCode: 23,
    transactionNameAr: 'قسط سلفة',
    transactionNameEn: 'Loan Installment',
    transactionType: 'DEDUCTION',
    isSystem: true,
  },
  {
    transactionCode: 24,
    transactionNameAr: 'حسم إجازة طارئة',
    transactionNameEn: 'Emergency Leave Deduction',
    transactionType: 'DEDUCTION',
    isSystem: true,
  },
  {
    transactionCode: 25,
    transactionNameAr: 'حسم إجازة بدون راتب',
    transactionNameEn: 'Unpaid Leave Deduction',
    transactionType: 'DEDUCTION',
    isSystem: true,
  },
];

export const mockSystemLogs: SystemLog[] = [
  {
    logId: 1,
    userId: '1234567890',
    actionType: 'LOGIN',
    module: 'Authentication',
    description: 'User logged in successfully',
    level: 'INFO',
    timestamp: new Date('2024-11-26T09:15:30'),
    ipAddress: '192.168.1.100',
  },
  {
    logId: 2,
    userId: '1234567890',
    actionType: 'CREATE',
    module: 'Employee Management',
    description: 'Created new employee record',
    level: 'INFO',
    timestamp: new Date('2024-11-26T10:30:45'),
    ipAddress: '192.168.1.100',
  },
  {
    logId: 3,
    userId: '1234567894',
    actionType: 'UPDATE',
    module: 'Payroll',
    description: 'Updated salary calculation for employee 1026',
    level: 'INFO',
    timestamp: new Date('2024-11-26T11:20:15'),
    ipAddress: '192.168.1.105',
  },
  {
    logId: 4,
    userId: '1234567890',
    actionType: 'DELETE',
    module: 'Projects',
    description: 'Attempted to delete project without proper permissions',
    level: 'WARNING',
    timestamp: new Date('2024-11-26T12:45:00'),
    ipAddress: '192.168.1.100',
  },
  {
    logId: 5,
    userId: '1234567899',
    actionType: 'APPROVE',
    module: 'Approvals',
    description: 'Approved leave request #3001',
    level: 'INFO',
    timestamp: new Date('2024-11-26T13:10:30'),
    ipAddress: '192.168.1.110',
  },
  {
    logId: 6,
    userId: '1234567890',
    actionType: 'EXPORT',
    module: 'Reports',
    description: 'Exported monthly payroll report',
    level: 'INFO',
    timestamp: new Date('2024-11-26T14:00:00'),
    ipAddress: '192.168.1.100',
  },
  {
    logId: 7,
    userId: '1234567894',
    actionType: 'ERROR',
    module: 'Database',
    description: 'Failed to connect to database server',
    level: 'ERROR',
    timestamp: new Date('2024-11-26T15:30:20'),
    ipAddress: '192.168.1.105',
  },
  {
    logId: 8,
    userId: '1234567909',
    actionType: 'VIEW',
    module: 'Projects',
    description: 'Viewed project details for project 1001',
    level: 'DEBUG',
    timestamp: new Date('2024-11-26T16:15:45'),
    ipAddress: '192.168.1.120',
  },
  {
    logId: 9,
    userId: '1234567890',
    actionType: 'UPDATE',
    module: 'System Settings',
    description: 'Updated system configuration',
    level: 'WARNING',
    timestamp: new Date('2024-11-26T17:00:10'),
    ipAddress: '192.168.1.100',
  },
  {
    logId: 10,
    userId: '1234567894',
    actionType: 'LOGOUT',
    module: 'Authentication',
    description: 'User logged out',
    level: 'INFO',
    timestamp: new Date('2024-11-26T18:30:00'),
    ipAddress: '192.168.1.105',
  },
];

// Mock Employee Contract Allowances
export const mockEmployeeContractAllowances: EmployeeContractAllowance[] = [
  {
    recordId: 1,
    employeeId: 1001,
    transactionCode: 1,
    transactionName: 'Basic Salary',
    percentage: 40,
    isActive: true,
    createdDate: new Date('2024-01-15'),
  },
  {
    recordId: 2,
    employeeId: 1001,
    transactionCode: 2,
    transactionName: 'Housing Allowance',
    percentage: 30,
    isActive: true,
    createdDate: new Date('2024-01-15'),
  },
  {
    recordId: 3,
    employeeId: 1001,
    transactionCode: 3,
    transactionName: 'Transportation Allowance',
    percentage: 20,
    isActive: true,
    createdDate: new Date('2024-01-15'),
  },
  {
    recordId: 4,
    employeeId: 1001,
    transactionCode: 4,
    transactionName: 'Food Allowance',
    percentage: 10,
    isActive: true,
    createdDate: new Date('2024-01-15'),
  },
  {
    recordId: 5,
    employeeId: 1002,
    transactionCode: 1,
    transactionName: 'Basic Salary',
    percentage: 50,
    isActive: true,
    createdDate: new Date('2024-02-01'),
  },
  {
    recordId: 6,
    employeeId: 1002,
    transactionCode: 2,
    transactionName: 'Housing Allowance',
    percentage: 25,
    isActive: true,
    createdDate: new Date('2024-02-01'),
  },
  {
    recordId: 7,
    employeeId: 1002,
    transactionCode: 3,
    transactionName: 'Transportation Allowance',
    percentage: 15,
    isActive: true,
    createdDate: new Date('2024-02-01'),
  },
  {
    recordId: 8,
    employeeId: 1002,
    transactionCode: 4,
    transactionName: 'Food Allowance',
    percentage: 10,
    isActive: true,
    createdDate: new Date('2024-02-01'),
  },
];

// Mock Allowance Percentages
export const mockAllowancePercentages: AllowancePercentage[] = [
  {
    recordId: 1,
    transactionCode: 1,
    transactionName: 'Basic Salary',
    saudiPercentage: 40,
    nonSaudiPercentage: 50,
    isActive: true,
  },
  {
    recordId: 2,
    transactionCode: 2,
    transactionName: 'Housing Allowance',
    saudiPercentage: 30,
    nonSaudiPercentage: 25,
    isActive: true,
  },
  {
    recordId: 3,
    transactionCode: 3,
    transactionName: 'Transportation Allowance',
    saudiPercentage: 20,
    nonSaudiPercentage: 15,
    isActive: true,
  },
  {
    recordId: 4,
    transactionCode: 4,
    transactionName: 'Food Allowance',
    saudiPercentage: 10,
    nonSaudiPercentage: 10,
    isActive: true,
  },
];

// Mock Manual Attendance Requests
export const mockManualAttendanceRequests: ManualAttendanceRequest[] = [
  {
    requestId: 1,
    employeeId: 1001,
    employeeName: 'Ahmed Ali',
    attendanceDate: new Date('2024-11-25'),
    entryTime: '08:15',
    exitTime: '17:30',
    reason: 'GPS signal was weak at project site',
    requestStatus: 'PENDING',
    requestedBy: 1001,
    requestedDate: new Date('2024-11-25T08:20:00'),
  },
  {
    requestId: 2,
    employeeId: 1002,
    employeeName: 'Mohammed Hassan',
    attendanceDate: new Date('2024-11-24'),
    entryTime: '07:45',
    exitTime: '16:20',
    reason: 'Forgot to check in, was at project site',
    requestStatus: 'APPROVED',
    requestedBy: 1002,
    requestedDate: new Date('2024-11-24T09:00:00'),
    approvedBy: 2001,
    approvedDate: new Date('2024-11-24T10:30:00'),
  },
  {
    requestId: 3,
    employeeId: 1003,
    employeeName: 'Omar Ibrahim',
    attendanceDate: new Date('2024-11-23'),
    entryTime: '08:00',
    exitTime: '17:00',
    reason: 'Phone battery died',
    requestStatus: 'REJECTED',
    requestedBy: 1003,
    requestedDate: new Date('2024-11-23T18:00:00'),
    approvedBy: 2001,
    approvedDate: new Date('2024-11-23T19:00:00'),
    rejectionReason: 'Request submitted after 60-minute grace period',
  },
];

// Mock Attendance Day Closures
export const mockAttendanceDayClosures: AttendanceDayClosure[] = [
  {
    closureId: 1,
    attendanceDate: new Date('2024-11-20'),
    isClosed: true,
    closedBy: 1234567890,
    closedDate: new Date('2024-11-20T23:00:00'),
  },
  {
    closureId: 2,
    attendanceDate: new Date('2024-11-21'),
    isClosed: true,
    closedBy: 1234567890,
    closedDate: new Date('2024-11-21T23:00:00'),
  },
  {
    closureId: 3,
    attendanceDate: new Date('2024-11-22'),
    isClosed: true,
    closedBy: 1234567890,
    closedDate: new Date('2024-11-22T23:00:00'),
  },
  {
    closureId: 4,
    attendanceDate: new Date('2024-11-23'),
    isClosed: false,
  },
  {
    closureId: 5,
    attendanceDate: new Date('2024-11-24'),
    isClosed: false,
  },
];

// Mock Project GPS Settings
export const mockProjectGPSSettings: ProjectGPSSettings[] = [
  {
    projectCode: 1001,
    latitude: 24.7136,
    longitude: 46.6753,
    attendanceRadius: 500,
    lastUpdated: new Date('2024-11-01'),
    updatedBy: 1234567890,
  },
  {
    projectCode: 1002,
    latitude: 24.7136,
    longitude: 46.6753,
    attendanceRadius: 1000,
    lastUpdated: new Date('2024-11-01'),
    updatedBy: 1234567890,
  },
  {
    projectCode: 1003,
    latitude: 24.7136,
    longitude: 46.6753,
    attendanceRadius: 750,
    lastUpdated: new Date('2024-11-01'),
    updatedBy: 1234567890,
  },
];

