// Arabic localization for Material React Table
export const mrtArabicLocalization = {
  actions: 'الإجراءات',
  and: 'و',
  cancel: 'إلغاء',
  changeFilterMode: 'تغيير وضع التصفية',
  changeSearchMode: 'تغيير وضع البحث',
  clearFilter: 'مسح التصفية',
  clearFilters: 'مسح الفلاتر',
  clearSearch: 'مسح البحث',
  clearSort: 'مسح الترتيب',
  clickToCopy: 'انقر للنسخ',
  collapse: 'طي',
  collapseAll: 'طي الكل',
  columnActions: 'إجراءات العمود',
  copiedToClipboard: 'تم النسخ إلى الحافظة',
  dropToGroupBy: 'اسحب للتجميع حسب {column}',
  edit: 'تعديل',
  expand: 'توسيع',
  expandAll: 'توسيع الكل',
  export: 'تصدير',
  exportToCSV: 'تصدير إلى CSV',
  exportToExcel: 'تصدير إلى Excel',
  exportToPDF: 'تصدير إلى PDF',
  filter: 'تصفية',
  filterArrBy: 'تصفية حسب {filterValue}',
  filterBy: 'تصفية حسب {column}',
  filterModePlaceholder: 'وضع التصفية',
  filters: 'التصفيات',
  grouping: 'التجميع',
  groupedBy: 'مجمّع حسب',
  hideAll: 'إخفاء الكل',
  hideColumn: 'إخفاء العمود',
  max: 'الحد الأقصى',
  min: 'الحد الأدنى',
  move: 'نقل',
  noDataToDisplay: 'لا توجد بيانات للعرض',
  noRecordsToDisplay: 'لا توجد سجلات للعرض',
  noResultsFound: 'لم يتم العثور على نتائج',
  of: 'من',
  or: 'أو',
  pinToLeft: 'تثبيت على اليسار',
  pinToRight: 'تثبيت على اليمين',
  print: 'طباعة',
  refresh: 'تحديث',
  resetColumnSize: 'إعادة تعيين حجم العمود',
  resetOrder: 'إعادة تعيين الترتيب',
  rowActions: 'إجراءات الصف',
  rowNumber: '#',
  rowNumbers: 'أرقام الصفوف',
  rowsPerPage: 'الصفوف لكل صفحة',
  save: 'حفظ',
  search: 'بحث',
  searchColumns: 'بحث في الأعمدة',
  select: 'اختيار',
  selectAll: 'تحديد الكل',
  deselectAll: 'إلغاء تحديد الكل',
  selectedCountOfRowCountRowsSelected: '{selectedCount} من {rowCount} صفوف محددة',
  showAll: 'إظهار الكل',
  showAllColumns: 'إظهار جميع الأعمدة',
  showColumns: 'إظهار الأعمدة',
  showHideColumns: 'إظهار/إخفاء الأعمدة',
  showHideFilters: 'إظهار/إخفاء التصفيات',
  showHideSearch: 'إظهار/إخفاء البحث',
  showingXOfY: 'عرض {x} من {y}',
  sort: 'ترتيب',
  sortAscending: 'تصاعدي',
  sortDescending: 'تنازلي',
  sortByColumnAsc: 'ترتيب تصاعدي حسب {column}',
  sortByColumnDesc: 'ترتيب تنازلي حسب {column}',
  sortedByColumnAsc: 'مرتب تصاعدياً حسب {column}',
  sortedByColumnDesc: 'مرتب تنازلياً حسب {column}',
  thenBy: 'ثم حسب',
  toggleDensity: 'تبديل الكثافة',
  toggleFullScreen: 'تبديل ملء الشاشة',
  toggleSelectAll: 'تبديل تحديد الكل',
  toggleSelectRow: 'تبديل تحديد الصف',
  ungroupByColumn: 'إلغاء التجميع حسب {column}',
  unpin: 'إلغاء التثبيت',
  unsorted: 'غير مرتب',
};
